[package]
name = "opensl-sys"
version = "0.1.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
license = "MIT"
description = "FFI bindings to OpenSL ES"
repository = "https://github.com/rust-av/opensl-rs"

build = "build.rs"

[build-dependencies]
bindgen = "0.59"

[dependencies]
